name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '17'

      - name: Checkout another Repo
        uses: actions/checkout@v4
        with:
            repository: krdyial/techproedsummer2020
            ref: master
      - name: Other step
        run:  |  
              pwd
              echo " Before"
              ls
              echo "Middle"
              echo "After"
            
              

     

